angel_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: ANGELUserBundle:Default:index }

angel_user_index:
    path:     /user/index
    defaults: { _controller: ANGELUserBundle:User:index } 

angel_user_add:
    path:     /user/add
    defaults: { _controller: ANGELUserBundle:User:add }   

angel_user_edit:
    path:     /user/edit/{id}
    defaults: { _controller: ANGELUserBundle:User:edit}          

angel_user_view:
    path:     /user/view/{id}
    defaults: { _controller: ANGELUserBundle:User:view}     

angel_user_delete:
    path:     /user/delete/{id}
    defaults: { _controller: ANGELUserBundle:User:delete}     